version: "3.7"

services:
  web-ssr:
    container_name: web_ssr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - /usr/ssrApp/node_modules
    #   - .:/usr/ssrApp
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
